;;; option 模块测试
(require 'option)

(check '(some 1) (some 1))
(check #t (some? (some 1)))
(check #f (some? 'none))
(check #t (none? 'none))
(check #f (none? (some 1)))
(check '(some 2) (option-map (lambda (x) (+ x 1)) (some 1)))
(check 'none (option-map (lambda (x) (+ x 1)) 'none))
(check '(some 2) (option-bind (some 1) (lambda (x) (some (+ x 1)))))
(check 'none (option-bind 'none (lambda (x) (some (+ x 1)))))
(check 'none (option-bind (some 1) (lambda (x) 'none)))
(check 42 (option-get (some 42)))
(check 42 (option-get-or (some 42) 0))
(check 0 (option-get-or 'none 0))
(check '(some 4) (option-filter even? (some 4)))
(check 'none (option-filter even? (some 3)))
(check 'none (option-filter even? 'none))
(check '(1) (option->list (some 1)))
(check '() (option->list 'none))

(define iter-log '())
(option-iter (lambda (v) (set! iter-log (cons v iter-log))) (some 7))
(check '(7) iter-log)
(option-iter (lambda (v) (set! iter-log (cons v iter-log))) 'none)
(check '(7) iter-log)
